# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#############################################################


# Configuration for Example Snap

logging:
 level: debug
greeting: "Configured Hello"

