# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#############################################################
# Test configuration for config
logging:
  level: debug
tls:
  allowPeerConfig: true
  enableSystemCertPool: true  
  caCerts:
  - "ca1"
  - "ca2"
  clientCert: "testCrt"
  namedClientOverride:
   abc:
     ca: "abcCA"
     crt: "abcCert"

httpclient:
  timeout: 
    client:
      timeout: 10s
    transport:
      tlsHandshake: 3s
      responseHeader: 5s
      expectContinue: 5s
      idleConn: 10s
    dialer:
      timeout: 10s
      keepAlive: 10s
  cache:
    refreshInterval: 30s

schemas:
  - type: application/json
    request: '{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Request Schema",
    "description": "Some product",
    "type": "object"}'
    response: '{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Response Schema"}'

headers: 
  - Content-Type
  - Authorization
