# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#############################################################


# Test configuration for config

logging:
  level: debug
tls:
  caCerts:
  - "ca1"
  - "ca2"
  clientCert: "testCrt"
  clientKey: "testKey"
  namedClientOverride:
   abc:
     ca: "abcCA"
     crt: "abcCert"
     key: "abcKey"
    
schemas:
  - type: application/json
    request: '{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Request Schema",
    "description": "Some product",
    "type": "object"}'
    response: '{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Response Schema"}'