// Code generated by protoc-gen-go.
// source: snap.proto
// DO NOT EDIT!

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	snap.proto

It has these top-level messages:
	Request
	Response
*/
package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	SnapName string   `protobuf:"bytes,1,opt,name=snapName" json:"snapName,omitempty"`
	Args     [][]byte `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Response struct {
	Error   string   `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Payload [][]byte `protobuf:"bytes,2,rep,name=payload,proto3" json:"payload,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*Request)(nil), "snapprotos.Request")
	proto.RegisterType((*Response)(nil), "snapprotos.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Snap service

type SnapClient interface {
	Invoke(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type snapClient struct {
	cc *grpc.ClientConn
}

func NewSnapClient(cc *grpc.ClientConn) SnapClient {
	return &snapClient{cc}
}

func (c *snapClient) Invoke(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/snapprotos.Snap/Invoke", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Snap service

type SnapServer interface {
	Invoke(context.Context, *Request) (*Response, error)
}

func RegisterSnapServer(s *grpc.Server, srv SnapServer) {
	s.RegisterService(&_Snap_serviceDesc, srv)
}

func _Snap_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/snapprotos.Snap/Invoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapServer).Invoke(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Snap_serviceDesc = grpc.ServiceDesc{
	ServiceName: "snapprotos.Snap",
	HandlerType: (*SnapServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _Snap_Invoke_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("snap.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x54, 0x8e, 0xb1, 0x4f, 0x85, 0x30,
	0x10, 0xc6, 0x7d, 0xfa, 0x04, 0xbc, 0x38, 0x9d, 0x0c, 0x84, 0x89, 0x30, 0xb1, 0x58, 0x8c, 0xc6,
	0x41, 0x13, 0x17, 0x37, 0x17, 0x87, 0xba, 0xb9, 0x15, 0x3c, 0x91, 0x20, 0x6d, 0xed, 0x81, 0x09,
	0xff, 0xbd, 0xa1, 0x45, 0xcd, 0x5b, 0xda, 0xef, 0x77, 0x97, 0x5f, 0xee, 0x03, 0x60, 0xad, 0xac,
	0xb0, 0xce, 0x4c, 0x06, 0x7d, 0xf6, 0x91, 0xcb, 0x3b, 0x88, 0x25, 0x7d, 0xcd, 0xc4, 0x13, 0xe6,
	0x90, 0xac, 0x8b, 0x67, 0x35, 0x52, 0xb6, 0x2b, 0x76, 0xd5, 0x99, 0xfc, 0x63, 0x44, 0xd8, 0x2b,
	0xd7, 0x71, 0x76, 0x5c, 0x9c, 0x54, 0xe7, 0xd2, 0xe7, 0xf2, 0x1e, 0x12, 0x49, 0x6c, 0x8d, 0x66,
	0xc2, 0x14, 0x4e, 0xc9, 0x39, 0xe3, 0x36, 0x31, 0x00, 0x66, 0x10, 0x5b, 0xb5, 0x7c, 0x1a, 0xf5,
	0xb6, 0x89, 0xbf, 0x78, 0xfd, 0x00, 0xfb, 0x17, 0xad, 0x2c, 0xde, 0x42, 0xf4, 0xa4, 0xbf, 0xcd,
	0x40, 0x78, 0x21, 0xfe, 0x5b, 0x89, 0xad, 0x52, 0x9e, 0x1e, 0x0e, 0xc3, 0xb1, 0xf2, 0xe8, 0xf1,
	0xea, 0x55, 0x74, 0xfd, 0xf4, 0x31, 0x37, 0xa2, 0x35, 0x63, 0xcd, 0xd4, 0xce, 0x8e, 0x06, 0x5a,
	0xea, 0x77, 0xd5, 0xb8, 0xbe, 0xbd, 0x5c, 0x25, 0xae, 0xc3, 0x1b, 0xe4, 0x26, 0xf2, 0xff, 0xcd,
	0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9b, 0xe8, 0xdd, 0xe3, 0x08, 0x01, 0x00, 0x00,
}
